# -*- coding: utf-8 -*-
"""Kode_FFT_Convolution_Ahmad Daffa Abiyyu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a190CXFDrbt8yLPZYTkfPu2cmASOORL0
"""

import numpy as np
import matplotlib.pyplot as plt

f = np.array([0, 1, 2, 3, 4, 5, 6])
g = np.array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

N1 = len(f)
N2 = len(g)

f_padded = np.pad(f, (0, N2 - 1), 'constant')
g_padded = np.pad(g, (0, N1 - 1), 'constant')

F_k = np.fft.fft(f_padded)
G_k = np.fft.fft(g_padded)

Y_k = F_k * G_k

y = np.fft.ifft(Y_k)

y_real = np.real(y)

plt.figure(figsize=(15, 12))

plt.subplot(3, 3, 1)
plt.stem(range(N1), f, basefmt=" ")
plt.title('f[n]')
plt.xlabel('Time Index (n)')
plt.ylabel('Amplitude')

plt.subplot(3, 3, 2)
plt.stem(range(N2), g, basefmt=" ")
plt.title('g[n]')
plt.xlabel('Time Index (n)')
plt.ylabel('Amplitude')

plt.subplot(3, 3, 3)
plt.stem(range(len(y_real)), y_real, basefmt=" ")
plt.title('Convolution Result')
plt.xlabel('Time Index (n)')
plt.ylabel('Amplitude')

plt.tight_layout()
plt.show()

convolution_result = np.convolve(f, g, mode='full')

print("Convolution result using FFT:", y_real)
print("Convolution result using numpy.convolve:", convolution_result)

